# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 462)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.plot = RenderArea(self.centralwidget)
        self.plot.setObjectName("plot")
        self.gridLayout.addWidget(self.plot, 0, 1, 6, 1)
        self.CloseCommBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CloseCommBtn.setObjectName("CloseCommBtn")
        self.gridLayout.addWidget(self.CloseCommBtn, 1, 0, 1, 1)
        self.StartMeasBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StartMeasBtn.setObjectName("StartMeasBtn")
        self.gridLayout.addWidget(self.StartMeasBtn, 4, 0, 1, 1)
        self.OpenCommBtn = QtWidgets.QPushButton(self.centralwidget)
        self.OpenCommBtn.setObjectName("OpenCommBtn")
        self.gridLayout.addWidget(self.OpenCommBtn, 0, 0, 1, 1)
        self.StopMeasBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StopMeasBtn.setObjectName("StopMeasBtn")
        self.gridLayout.addWidget(self.StopMeasBtn, 5, 0, 1, 1)
        self.VersionBtn = QtWidgets.QPushButton(self.centralwidget)
        self.VersionBtn.setObjectName("VersionBtn")
        self.gridLayout.addWidget(self.VersionBtn, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.IntTimeEdt = QtWidgets.QLineEdit(self.groupBox)
        self.IntTimeEdt.setGeometry(QtCore.QRect(10, 60, 51, 20))
        self.IntTimeEdt.setObjectName("IntTimeEdt")
        self.NumAvgEdt = QtWidgets.QLineEdit(self.groupBox)
        self.NumAvgEdt.setGeometry(QtCore.QRect(10, 120, 51, 20))
        self.NumAvgEdt.setObjectName("NumAvgEdt")
        self.NumMeasEdt = QtWidgets.QLineEdit(self.groupBox)
        self.NumMeasEdt.setGeometry(QtCore.QRect(10, 180, 51, 20))
        self.NumMeasEdt.setObjectName("NumMeasEdt")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 311, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 85, 311, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 145, 311, 21))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.OpenCommBtn, self.CloseCommBtn)
        MainWindow.setTabOrder(self.CloseCommBtn, self.VersionBtn)
        MainWindow.setTabOrder(self.VersionBtn, self.IntTimeEdt)
        MainWindow.setTabOrder(self.IntTimeEdt, self.NumAvgEdt)
        MainWindow.setTabOrder(self.NumAvgEdt, self.NumMeasEdt)
        MainWindow.setTabOrder(self.NumMeasEdt, self.StartMeasBtn)
        MainWindow.setTabOrder(self.StartMeasBtn, self.StopMeasBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CloseCommBtn.setText(_translate("MainWindow", "Close Communication"))
        self.StartMeasBtn.setText(_translate("MainWindow", "Start Measurements"))
        self.OpenCommBtn.setText(_translate("MainWindow", "Open Communication"))
        self.StopMeasBtn.setText(_translate("MainWindow", "Stop Measurements"))
        self.VersionBtn.setText(_translate("MainWindow", "Show Version Info"))
        self.groupBox.setTitle(_translate("MainWindow", "Measurement Parameters"))
        self.label.setText(_translate("MainWindow", "Integration Time [ms]"))
        self.label_2.setText(_translate("MainWindow", "Number of Averages"))
        self.label_3.setText(_translate("MainWindow", "Number of Measurements"))
from renderarea import RenderArea
